Repository aviabird/angularspree, pull requests merged in 2018-09, with the labels that each got.

#244 Refactor phase 1
  src/app/app.component.ts
  src/app/app.reducers.ts
  src/app/app_preloading_strategy.ts
  src/app/auth/actions/auth.actions.ts
  src/app/auth/components/sign-up/sign-up.component.ts
  src/app/auth/components/update-password/update-password.component.ts
  src/app/auth/effects/auth.effects.ts
  src/app/auth/reducers/auth.reducer.ts
  src/app/checkout/actions/checkout.actions.ts
  src/app/checkout/address/add-address/add-address.component.html
  src/app/checkout/address/add-address/add-address.component.ts
  src/app/checkout/address/services/address.service.ts
  src/app/checkout/cart/cart.component.ts
  src/app/checkout/cart/components/line-item-list/line-item/line-item.component.ts
  src/app/checkout/effects/checkout.effects.ts
  src/app/checkout/order-failed/order-failed.component.html
  src/app/checkout/order-failed/order-failed.component.ts
  src/app/checkout/order-success/order-success.component.html
  src/app/checkout/order-success/order-success.component.scss
  src/app/checkout/order-success/order-success.component.ts
  src/app/checkout/payment/payment-modes-list/payment-modes-list.component.ts
  src/app/checkout/reducers/checkout.state.ts
  src/app/checkout/reducers/selectors.ts
  src/app/core/models/address.ts
  src/app/core/models/state.ts
  src/app/core/models/user.ts
  src/app/core/pipes/humanize.pipe.ts
  src/app/core/services/auth.service.ts
  src/app/core/services/checkout.service.ts
  src/app/landing/components/brands-page/brands-page.component.html
  src/app/landing/components/brands-page/brands-page.component.ts
  src/app/landing/components/lp-brands/lp-brands.component.ts
  src/app/landing/components/lp-product-list/lp-product-list.component.html
  src/app/landing/components/lp-product-list/lp-product-list.component.ts
  src/app/landing/components/lp-product-list/pl-item/pl-item.component.html
  src/app/landing/components/lp-product-list/pl-item/pl-item.component.ts
  src/app/landing/landing-routing.module.ts
  src/app/landing/landing.component.html
  src/app/landing/landing.component.scss
  src/app/layout/footer/component/footer-quick-links/footer-quick-links.component.html
  src/app/layout/header/components/brand-menu-dropdown/brand-componant/brand-list/brand-list.component.ts
  src/app/layout/header/components/brand-menu-dropdown/brand-menu-dropdown.component.ts
  src/app/layout/header/components/categories-menu-dropdown/categories-components/categories-details/brand-logo/brand-logo.component.ts
  src/app/layout/header/components/categories-menu-dropdown/categories-components/categories-details/categories-details.component.html
  src/app/layout/header/components/categories-menu-dropdown/categories-components/categories-details/categories-details.component.ts
  src/app/layout/header/components/categories-menu-dropdown/categories-components/categories-details/categories-list/categories-list.component.ts
  src/app/layout/header/components/categories-menu-dropdown/categories-menu-dropdown.component.ts
  src/app/layout/header/components/category-mobile-menu/category-mobile-menu.component.ts
  src/app/layout/header/components/header-cart/header-cart.component.ts
  src/app/layout/header/components/header-help-dropdown/header-help-dropdown.component.html
  src/app/layout/header/components/header-help-dropdown/header-help-dropdown.component.ts
  src/app/layout/header/components/header-search/header-search.component.ts
  src/app/layout/header/components/profile-dropdown/profile-dropdown.component.html
  src/app/layout/header/components/profile-dropdown/profile-dropdown.component.ts
  src/app/layout/header/header.component.scss
  src/app/layout/header/header.component.ts
  src/app/user/components/addresses/add-edit-address/add-edit-address.component.ts
  src/app/user/services/user.service.ts
  src/config/custom.example/app-data.ts
  src/config/default/app-data.ts
Labels: Ready for merge, enhancement

#252 Refactor/phase 2
  src/app/app.component.scss
  src/app/app.component.ts
  src/app/auth/components/login/login.component.ts
  src/app/auth/components/sign-up/sign-up.component.html
  src/app/auth/components/sign-up/sign-up.component.ts
  src/app/auth/components/update-password/update-password.component.ts
  src/app/auth/effects/auth.effects.ts
  src/app/checkout/address/add-address/add-address.component.html
  src/app/checkout/address/address.component.html
  src/app/checkout/address/delivery-options/delivery-options.component.ts
  src/app/checkout/address/services/address.service.ts
  src/app/checkout/cart/components/line-item-list/line-item/line-item.component.ts
  src/app/checkout/order-failed/order-failed.component.ts
  src/app/checkout/order-success/order-success.component.ts
  src/app/checkout/payment/payment-modes-list/payment-modes-list.component.ts
  src/app/checkout/payment/payment.component.ts
  src/app/checkout/reducers/selectors.ts
  src/app/core/services/auth.service.ts
  src/app/core/services/checkout.service.ts
  src/app/core/services/product.service.ts
  src/app/core/services/variant-parser.service.ts
  src/app/home/category-page/category-page.component.ts
  src/app/home/content/content-header/content-header.component.html
  src/app/home/content/content-header/content-header.component.ts
  src/app/home/content/content.ts
  src/app/home/home.component.html
  src/app/home/home.component.ts
  src/app/landing/components/lp-banner/lp-banner.component.scss
  src/app/layout/header/header.component.scss
  src/app/user/services/user.service.ts
Labels: In Progress, bug, do not merge

#260 Cod order products images
  src/app/app.component.ts
  src/app/checkout/actions/checkout.actions.ts
  src/app/checkout/address/address.component.ts
  src/app/checkout/address/delivery-options/delivery-options.component.html
  src/app/checkout/address/delivery-options/delivery-options.component.ts
  src/app/checkout/cart/components/line-item-list/line-item/line-item.component.html
  src/app/checkout/cart/components/line-item-list/line-item/line-item.component.ts
  src/app/checkout/effects/checkout.effects.ts
  src/app/checkout/order-success/order-success.component.html
  src/app/checkout/order-success/order-success.component.ts
  src/app/checkout/payment/payment-modes-list/cash-on-delivery/cash-on-delivery.component.html
  src/app/checkout/payment/payment-modes-list/cash-on-delivery/cash-on-delivery.component.ts
  src/app/checkout/payment/payment-modes-list/credit-card/credit-card.component.html
  src/app/checkout/payment/payment-modes-list/payment-modes-list.component.html
  src/app/checkout/payment/payment-modes-list/payment-modes-list.component.ts
  src/app/checkout/payment/services/payment.service.ts
  src/app/checkout/reducers/checkout.reducer.ts
  src/app/checkout/reducers/checkout.state.ts
  src/app/checkout/reducers/selectors.ts
  src/app/core/interceptors/token.interceptor.ts
  src/app/core/models/order.ts
  src/app/core/models/product.ts
  src/app/core/services/checkout.service.ts
  src/app/product/components/product-detail-page/product-details/product-details.component.ts
  src/app/product/components/product-detail-page/product-images/product-images.component.html
  src/app/product/components/product-detail-page/product-variants/product-variants.component.html
  src/app/shared/components/product-slider/inner-product/inner-product.component.ts
  src/app/user/services/user.service.ts
Labels: Ready for merge

#261 Modified payment process & other fixes
  src/app/checkout/actions/checkout.actions.ts
  src/app/checkout/address/address.component.html
  src/app/checkout/address/address.component.ts
  src/app/checkout/address/delivery-options/delivery-options.component.ts
  src/app/checkout/cart/cart.component.ts
  src/app/checkout/cart/components/line-item-list/line-item/line-item.component.ts
  src/app/checkout/effects/checkout.effects.ts
  src/app/checkout/payment/payment-modes-list/cash-on-delivery/cash-on-delivery.component.html
  src/app/checkout/payment/payment-modes-list/cash-on-delivery/cash-on-delivery.component.ts
  src/app/checkout/payment/payment-modes-list/credit-card/credit-card.component.html
  src/app/checkout/payment/payment-modes-list/credit-card/credit-card.component.spec.ts
  src/app/checkout/payment/payment-modes-list/credit-card/credit-card.component.ts
  src/app/checkout/payment/payment-modes-list/hosted-payment/hosted-payment.component.html
  src/app/checkout/payment/payment-modes-list/hosted-payment/hosted-payment.component.scss
  src/app/checkout/payment/payment-modes-list/hosted-payment/hosted-payment.component.spec.ts
  src/app/checkout/payment/payment-modes-list/hosted-payment/hosted-payment.component.ts
  src/app/checkout/payment/payment-modes-list/net-banking/net-banking.component.html
  src/app/checkout/payment/payment-modes-list/net-banking/net-banking.component.scss
  src/app/checkout/payment/payment-modes-list/net-banking/net-banking.component.ts
  src/app/checkout/payment/payment-modes-list/payment-mode/payment-mode.component.html
  src/app/checkout/payment/payment-modes-list/payment-mode/payment-mode.component.scss
  src/app/checkout/payment/payment-modes-list/payment-mode/payment-mode.component.spec.ts
  src/app/checkout/payment/payment-modes-list/payment-mode/payment-mode.component.ts
  src/app/checkout/payment/payment-modes-list/payment-modes-list.component.html
  src/app/checkout/payment/payment-modes-list/payment-modes-list.component.ts
  src/app/checkout/payment/payment.component.html
  src/app/checkout/payment/payment.module.ts
  src/app/checkout/payment/services/payment.service.ts
  src/app/checkout/reducers/checkout.reducer.ts
  src/app/core/models/payment_mode.ts
  src/app/core/services/checkout.service.ts
  src/app/core/services/product.service.ts
  src/app/product/components/product-detail-page/product-details/product-details.component.ts
  src/app/product/components/product-detail-page/product-price-info/product-count/product-count.component.ts
Labels: Ready for merge
