Repository aviabird/angularspree, pull requests merged in 2018-04, with the labels that each got.

#90 Adding Google login
  package-lock.json
  package.json
  src/app/app.module.ts
  src/app/auth/actions/auth.actions.ts
  src/app/auth/components/login/login.component.html
  src/app/auth/components/login/login.component.ts
  src/app/auth/components/sign-up/sign-up.component.html
  src/app/auth/components/sign-up/sign-up.component.ts
  src/app/auth/effects/auth.effects.ts
  src/app/core/services/auth.service.ts
  src/app/oauth_config.ts
Labels: In Progress

#101 Added Shop by Category & brand
  src/app/core/services/auth.service.ts
  src/app/layout/header/components/brand-menu-dropdown/brand-componant/brand-list/brand-list.component.html
  src/app/layout/header/components/brand-menu-dropdown/brand-componant/brand-list/brand-list.component.scss
  src/app/layout/header/components/brand-menu-dropdown/brand-componant/brand-list/brand-list.component.spec.ts
  src/app/layout/header/components/brand-menu-dropdown/brand-componant/brand-list/brand-list.component.ts
  src/app/layout/header/components/brand-menu-dropdown/brand-menu-dropdown.component.html
  src/app/layout/header/components/brand-menu-dropdown/brand-menu-dropdown.component.scss
  src/app/layout/header/components/brand-menu-dropdown/brand-menu-dropdown.component.spec.ts
  src/app/layout/header/components/brand-menu-dropdown/brand-menu-dropdown.component.ts
  src/app/layout/header/components/categories-menu-dropdown/categories-components/categories-details/categories-details.component.html
  src/app/layout/header/components/categories-menu-dropdown/categories-components/categories-details/categories-details.component.scss
  src/app/layout/header/components/categories-menu-dropdown/categories-components/categories-details/categories-details.component.spec.ts
  src/app/layout/header/components/categories-menu-dropdown/categories-components/categories-details/categories-details.component.ts
  src/app/layout/header/components/categories-menu-dropdown/categories-components/categories-details/categories-list/categories-list.component.html
  src/app/layout/header/components/categories-menu-dropdown/categories-components/categories-details/categories-list/categories-list.component.scss
  src/app/layout/header/components/categories-menu-dropdown/categories-components/categories-details/categories-list/categories-list.component.spec.ts
  src/app/layout/header/components/categories-menu-dropdown/categories-components/categories-details/categories-list/categories-list.component.ts
  src/app/layout/header/components/categories-menu-dropdown/categories-menu-dropdown.component.html
  src/app/layout/header/components/categories-menu-dropdown/categories-menu-dropdown.component.scss
  src/app/layout/header/components/categories-menu-dropdown/categories-menu-dropdown.component.spec.ts
  src/app/layout/header/components/categories-menu-dropdown/categories-menu-dropdown.component.ts
  src/app/layout/header/header.component.html
  src/app/layout/header/header.component.ts
  src/app/layout/index.ts
  src/app/shared/data/app-data.ts
Labels: WIP

#107 Landing Page with Today's Deals & Customer Favourites
  src/app/core/services/product.service.ts
  src/app/home/landing/landing.component.html
  src/app/home/landing/landing.component.ts
  src/app/home/landing/lp-brands/lp-brands.component.html
  src/app/home/landing/lp-brands/lp-brands.component.ts
  src/app/home/landing/lp-favorites/lp-favorites.component.html
  src/app/home/landing/lp-favorites/lp-favorites.component.ts
  src/app/home/landing/lp-favorites/pl-fav-item/pl-fav-item.component.ts
  src/app/home/landing/lp-product-list/lp-product-list.component.html
  src/app/home/landing/lp-product-list/lp-product-list.component.ts
  src/app/home/landing/lp-promo/lp-promo.component.html
  src/app/home/landing/lp-videos/lp-videos.component.html
  src/app/layout/header/components/categories-menu-dropdown/categories-components/categories-details/categories-details.component.ts
  src/app/layout/header/header.component.html
  src/app/shared/data/app-data.ts
Labels: In Review, Ready for merge
